name: Clojure CI

on:
  push:
    branches:
      - EPC-16
  pull_request:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs-material

      - name: Install dependencies
        run: lein deps

      - name: Run tests
        run: lein with-profile test cloverage --runner :eftest --codecov

      - if: matrix.os == 'ubuntu-latest'
        name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/coverage/codecov.json
          flags: unittests
          name: epsilon-clj-unit
          fail_ci_if_error: true
          verbose: true

      #      - if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master'
      - if: matrix.os == 'ubuntu-latest'
        name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          user: 'aratare-jp'
          project: 'epsilon-clj'
          token: ${{ secrets.GH_CHANGELOG_TOKEN }}

      #      - if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master'
      - if: matrix.os == 'ubuntu-latest'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog
          file_pattern: CHANGELOG.md

      - if: matrix.os == 'ubuntu-latest'
        name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
          path: ./CHANGELOG.md

      - if: matrix.os == 'ubuntu-latest'
        run: echo "${{ steps.changelog_reader.outputs.changes }}"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs-material
      - run: pip install mkdocs-macros-plugin
      - run: pip install mike

      - run: |
          git config user.name "Rex Truong"
          git config user.email "rextruong@pm.me"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build Uberjar
        run: lein uberjar

      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
          path: ./CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: ${{ steps.changelog_reader.outputs.changes }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/uberjar/epsilon-${{ steps.get_version.outputs.VERSION }}-standalone.jar
          asset_name: epsilon-${{ steps.get_version.outputs.VERSION }}-standalone.jar
          asset_content_type: application/java-archive

      - name: Importing GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploying to Clojars
        run: |
          touch $LEIN_HOME/credentials.clj
          echo "{#\"https://repo.clojars.org\" {:username \"aratare\" :password \"${{ secrets.LEIN_DEPLOY_PASSWORD }}\"}}" > $LEIN_HOME/credentials.clj
          gpg --output $LEIN_HOME/credentials.clj.gpg --sign $LEIN_HOME/credentials.clj
          rm $LEIN_HOME/credentials.clj
          lein deploy clojars

      - name: Upload MKDocs
        run: |
          mike deploy -p -f ${{ steps.get_version.outputs.VERSION }} latest
          mike set-default -p -f latest