name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein with-profile test cloverage --runner :eftest --codecov
      - if: matrix.os == 'ubuntu-latest'
        name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/coverage/codecov.json
          flags: unittests
          name: epsilon-clj-unit
          fail_ci_if_error: true
          verbose: true
      - if: matrix.os == 'ubuntu-latest'
        name: Upload MKDocs
        run: mkdocs gh-deploy --force